remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"

title: "The Allies' Manifesto"
description: "A refuge against toxic behaviors and organizations."

logo: "/assets/images/logo.png"

plugins:
  - jekyll-redirect-from

aux_links:
  "🇬🇧": "/en/"
  "🇫🇷": "/fr/"