remote_theme: "pmarsceill/just-the-docs"
color_scheme: "dark"

title: "The Allies’ Manifesto"
description: "A refuge against toxic behaviors and organizations."
baseurl: "/manifesto"
url: "https://the-allies.github.io"

logo: "/assets/images/logo.png"

aux_links:
  "The Allies on GitHub": "https://github.com/the-allies"

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

# Footer configuration
back_to_top: true
back_to_top_text: "Back to top"
footer_content: 'Copyright &copy; 2026 The Allies. Distributed by a <a href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License (CC-BY 4.0)</a>. <a href="https://www.netlify.com/">This site is powered by Netlify.</a>'
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p" # ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/the-allies/manifesto"
gh_edit_branch: "main"
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately